name: Auto Merge Pull Requests

on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'

    steps:
      - name: Wait for checks to start
        run: sleep 20

      - name: Wait for CI to pass
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Build and Push Docker Image / build'
          repo-token: ${{ secrets.GHCR_PAT }}
          wait-interval: 15


      - name: Merge PR when labeled 'automerge'
        if: contains(github.event.pull_request.labels.*.name, 'automerge')
        uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true
